apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - image: {{ .Values.container.image.repository }}:{{ .Values.container.image.tag }}
        name: {{ .Chart.Name }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.container.port }}
        env:
        - name: USER_NAME
          value: {{ .Values.env.USER_NAME }}
