apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  ports:
  - port: {{ .Values.lb.port }}
    targetPort: {{ .Values.container.port }}
    protocol: TCP
  type: NodePort
  selector:
    app: {{ .Chart.Name }}
